### PR TITLE
Update screenshots to current version

### LINKED ISSUE #7: Update screenshots to current version
The screenshots used are form macOS 10.14 and should be re-taken under macOS 11

### PR DESCRIPTION
**Pull request by diepoe**
*This closes #7*

## 🍱 add new screenshots
I made new screenshots on the current MacPass version with macOS BigSur. For the full window screenshots, I sized the window to take 2/3 of my screen width and the full height (13inch MacBook Pro).

## 💄 update html and css for new screenshots
I just created a seperate directory for the screenshots and updated the paths to the images. I also added some missed attributes on the `img` elements (`alt` and `loading="lazy"`).

**I didn't got a fullsize searchscreen screenshot, because the search functionality wasn't working correctly on my machine. Maybe you could do one, or we still include the old**

## screenshot of the webpage with the new screenshots
preview

### CODE REVIEW

**Comment by mstarke** [comment]
Awesome. I would love to add those but I think I might have created additional work. The current release looks a lot different for macOS 11 upwards. I also might add the Demo.KDBX file to the repo to make contributions like yours easier.

**Comment by diepoe** [comment]
Ok, I could recreate them and the demo file would help a lot :) [I installed MacPass with brew, so I have to reinstall it again but that isn't a problem]

**Comment by mstarke** [comment]
@haudraufhaun do you still want to update the screenshots? I did finally push 0.8 so we now have an official version. Adding the new support for TOTP might also be an option.

**Comment by diepoe** [comment]
I can do it, maybe it takes a week or two because I'm busy with some exams right now 🤓. I'll close this pull request and do it on a totally new & fresh PR :)

**Comment by mstarke** [comment]
Awesome. Thank you!

**Pull request closed without merging**
