### PR TITLE
Add a plugin registry to the website

### PR DESCRIPTION
**Pull request by Floppy**
This is a suggestion for adding a minimal plugin registry to the macpass website, as part of a solution to https://github.com/mstarke/MacPass/issues/703 to allow warning on outdated plugins.

The PR does a few things:

* Uses [Jekyll](https://jekyllrb.com/) to build the pages, so we can share layout and data files around.
* Adds a data file for the plugin registry. This is available both within the site builder and at /data/plugins.json for the MacPass app itself to read.
* Adds a plugins page. This is currently unstyled, but I'll finish that off if you're open to the approach, @mstarke :)

Currently only MacPassHTTP is included in the registry. Plugin authors will need to manually update the registry with a PR when they release new versions.

### CODE REVIEW

**Comment by Floppy** [comment]
Hah! Just seen your commit, you're ahead of me already!

**Comment by mstarke** [comment]
Nice. I started a separate repo to publish the plugin.json and had a more complicated format in mind to enable a more sophisticated version checking.

**Comment by mstarke** [comment]
Can you rebase to incorporate the changes?

**Comment by Floppy** [comment]
rebase done 👍

**Comment by mstarke** [comment]
We can include compatibilty attributes as well so MacPass can disable non-working plugins

**Pull request merged**
